apiVersion: v2
name: dirigible
version: 1.0.2
description: Helm chart for Eclipse Dirigible setup
type: application
keywords:
  - dirigible
  - platform
  - eclipse
  - development
  - applications
  - in-system
home: https://github.com/dirigiblelabs/charts/tree/master/dirigible
maintainers:
  - email: yordan.pavlov@sap.com
    name: Yordan Pavlov
    url: https://github.com/ThuF
sources:
  - https://github.com/dirigiblelabs/charts
  - https://github.com/eclipse/dirigible/
icon: https://raw.githubusercontent.com/eclipse/dirigible/master/logo/dirigible-logo-symbol.png

